### ISSUE TITLE
Conveying the wrong message?

### ISSUE THREAD

**Issue by pennersr** [redecentralize/redecentralize-website#60]
I feel it is a bit ironic that while the site is advocating redecentralization, it promotes the use of GitHub.com and various other services -- all of which are key examples of a centralized Internet. To me, that is conveying the wrong message. What do you think?

[1] https://wubthecaptain.eu/github.html

**Comment by frabcus** [comment]
For us, usability trumps ideology. The only way to get mass takeup of decentralized solutions is if they are as easy to use as the centralized ones. While we could be puritanical and 

We do try to move to "decentralized" alternatives as they come available - but there aren't enough of them that are good enough yet. Hence the project! 

For example, we use Libre List rather than Google Groups. It isn't _actually_ more decentralized - it is still on a server in one place. So even where there are open source alternatives - like GitLab - they're not in practice properly decentralized yet.

**Comment by pennersr** [comment]
"usability trumps ideology" is exactly the reason why centralized sites thrive so well. It's not that people prefer giving up their privacy to use some service, it is simply more convenient above the alternatives.

As for GitHub, you could opt for moving to Gitorious (https://gitorious.org). It fits your decentralized vision in the sense that you can host a copy yourself (but you don't have to). Sure, it is less usable than Github. But, if even you are not willing to move to alternatives like these because they are not good enough, your target audience will never make the move. Alternatives will only improve once used.

Just my 2cts...

**Comment by frabcus** [comment]
Agree!

Gitlab would be my choice though.

**Comment by rossjones** [comment]
Does gitlab have a gh-pages clone?
